name = "redirects"
main = "src/index.ts"
compatibility_date = "2024-12-25"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV_NS"
id = "244d6be683ca409ba4da2d1d41f44917"
preview_id = "6d65e840b31e482896f9f9fc2fdcffa3"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
